### ISSUE TITLE
Issue with waveshare V3 screen

### ISSUE THREAD

**Issue by tPayne0647** [LoganMD/pwnagotchi-clock#4]
Trying to get this to work on waveshare v3. I was hoping all I needed to do was change-

` if ui.is_waveshare_v2():` to ` if ui.is_waveshare_3():`

but no luck...

**Comment by Big-Tom92** [comment]
First, check that waveshare v3 is defined `/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/display.py`
Should look like this, but add it if it's not there:
```
def is_waveshare_v3(self):
        return self._implementation.name == 'waveshare_3'
```
Then you should be able to work it with `if ui.is_waveshare_3():`

I got it working this way, but your results may vary. Lining things up is a bit of a pain if you're using memtemp as well, but happy to share my changes.

<img width="703" alt="Screenshot 2023-08-04 at 15 04 38" src="https://github.com/LoganMD/pwnagotchi-clock/assets/134062025/8508859e-69d1-4c49-9620-dd58ecd7965b">

**Comment by tPayne0647** [comment]
thank you! That worked! I'm only a few months into python, that totally makes sense though. Thanks for taking the time to look into it!
